name: free-v2ray-node

on:
  schedule:
    - cron: '0 * * * *'
  push:
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 转到 Settings > Secrets and variables > Actions
          # 点击 New repository secret，添加 Secret，名称为 BOT，输入你的token
          token: ${{ secrets.BOT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit and push file
        run: |
          set +e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 检查是否有文件变更
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add v2ray.txt all.txt v2ray_raw.txt
          git commit -m "update $(date '+%Y-%m-%d %H:%M:%S')"
          
          # 尝试正常推送
          if git push origin HEAD:master; then
            echo "Successfully pushed to master"
          else
            echo "Normal push failed, trying rebase..."
            git pull --rebase origin master
            if [ $? -eq 0 ]; then
              git push origin HEAD:master
              echo "Successfully pushed after rebase"
            else
              echo "Rebase failed, aborting..."
              git rebase --abort
              echo "Please check repository permissions and token settings"
              exit 1
            fi
          fi
